services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: back
      POSTGRES_USER: studbank
      POSTGRES_PASSWORD: ButterFLy777
    networks:
      - web
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fiveplus -d back"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - "db:/var/lib/postgresql/data"
    ports:
      - 5432:5432

  otelcol:
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ./otelcol-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension

  prom:
    image: prom/prometheus
    ports:
      - 9090:9090

networks:
  web:
    external: true


volumes:
  db:
    driver: local
