name: back-dev
version: v0.0.0-pre

log: 
  level: TRACE
  lokiAddress: http://gateway:3100
  lokiAuth: 
    login: ""
    password: ""

api:
    port: 8080
    ssl:
        on: true
        cert: envs/dev/sec/cert.pem
        key: envs/dev/sec/key.pem

    middlewares:
        cors:
            allowOrigins:
                - "*"
            allowMethods:
                - GET
                - PUT
                - POST
                - DELETE
                - PATCH
            allowHeaders:
                - "*"
            allowCredentials: true
            exposeHeaders:
                - "*"
            maxAge: 0
        csrf:
            tokenLength: 32
            tokenLookup: "header:X-CSRF-Token"
        secure:
          xss: 1; mode=block
          ctNosniff: nosniff
          xFrame: ""
          hstsMaxAge: 0
          hstsExclude: false
          csPolicy: ""

    metricsPort: 8081
    swaggePort: 8082

    auth: 
      secret: envs/dev/sec/jwt.key
      accessExpiary: 600 #s
      refreshExpiary: 2592000 #s

db:
  host: postgres
  port: 5432
  dbName: backend
  user: studbank
  password: envs/dev/sec/db.password
  ssl: false

tinkoff:
  terminalId: ""
  token: ""

